version: '3.5' 

services:
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: salasana

  backend:
    image: backend
    environment:
      - REDIS=redis
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=salasana
    depends_on:
      - redis
      - postgres

  frontend:
    image: frontend

  proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend