version: '3.5' 

services:
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: salasana
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    image: backend
    environment:
      - FRONT_URL=http://localhost
      - REDIS=redis
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=salasana
    depends_on:
      - redis
      - postgres

  frontend:
    image: frontend
    environment:
      - API_URL=http://localhost/api

  proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend