version: '3'
services:
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=salasana
  backend:
    image: 'backend'
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment:
      - REDIS=redis
      - DB_HOST=postgres
      - DB_USERNAME=postgres 
      - DB_PASSWORD=salasana
  frontend:
    image: 'frontend'
    ports:
      - 5000:5000